steps:
# build the docker image that contains bazel + android SDK
- name: gcr.io/cloud-builders/docker
  args: ['build', '--tag=gcr.io/$PROJECT_ID/bazel-android', '.']
# build the maven repository using bazel
#- name: gcr.io/$PROJECT_ID/bazel-android
#  args: ['build', '//:axt_m2repository']
# run the robolectric tests
- name: gcr.io/$PROJECT_ID/bazel-android
  args: ['test', '//core/...', '//ext/...', '//espresso/...', '//runner/...', '--test_tag_filters=robolectric', '--build_tag_filters=robolectric']
timeout: '1200s'
# use a 32 vCPU 28.8GB memory machine.
options:
  machineType: "N1_HIGHCPU_32"
