name: Build
on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check java version
        run: java --version
      - name: Build maven artifacts
        run: bazelisk build //:axt_m2repository

